version: "2"
services:
  mongo:
    image: mongo
    environment:
      - TERM=xterm-256color
    ports:
      - "27017:27017"
  loopback:
    build: .
    environment:
      - TERM=xterm-256color
    container_name: "my-AppBackEnd"
    links:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"